# Age estimation using weight and height in the baby boy dataset

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from GeneralizedRegressionNeuralNetworks import GRNN

### Create Baby boy data

In [2]:

weight =[2.8, 3.8 , 4.3 , 5.6 ,6.2,6.4,7,7.4,7.65,7.9,8.1,8.3,8.5] #Baby boy weight from birth to 1 year old (mean)[1]
weight = np.array(weight)

boy =[45.7,52.7,56,59,61,63.5,65.1,66.6,68,69.5,70.5,71.5,73]#Baby boy size from birth to 1 year(mean)[1]
boy=np.array(boy)


In [3]:
X = np.stack((weight, boy),axis=1)
X

array([[ 2.8 , 45.7 ],
       [ 3.8 , 52.7 ],
       [ 4.3 , 56.  ],
       [ 5.6 , 59.  ],
       [ 6.2 , 61.  ],
       [ 6.4 , 63.5 ],
       [ 7.  , 65.1 ],
       [ 7.4 , 66.6 ],
       [ 7.65, 68.  ],
       [ 7.9 , 69.5 ],
       [ 8.1 , 70.5 ],
       [ 8.3 , 71.5 ],
       [ 8.5 , 73.  ]])

In [4]:
age = np.arange(0,13,1)
y = age
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#### Split arrays or matrices into random train and test subsets


In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [6]:
X_train

array([[ 4.3, 56. ],
       [ 3.8, 52.7],
       [ 8.5, 73. ],
       [ 6.2, 61. ],
       [ 7.4, 66.6],
       [ 8.1, 70.5],
       [ 5.6, 59. ],
       [ 7. , 65.1]])

In [7]:
X_test

array([[ 8.3 , 71.5 ],
       [ 7.9 , 69.5 ],
       [ 2.8 , 45.7 ],
       [ 7.65, 68.  ],
       [ 6.4 , 63.5 ]])

In [8]:
y_train

array([ 2,  1, 12,  4,  7, 10,  3,  6])

In [9]:
y_test

array([11,  9,  0,  8,  5])

### Create model

In [10]:
model = GRNN(X_train,y_train,X_test,y_test)

In [11]:
print('Output                                 :',model.predict())
print('MSE                                    :',model.mean_squared_error())

Output                                 : [10.69727375  9.94091585  1.          7.25761362  5.71011515]
MSE                                    : [0.01832864 0.17706453 0.2        0.11022751 0.10085271]


In [12]:
np.stack((y_test, model.predict()),axis=1)

array([[11.        , 10.69727375],
       [ 9.        ,  9.94091585],
       [ 0.        ,  1.        ],
       [ 8.        ,  7.25761362],
       [ 5.        ,  5.71011515]])

**Resource**

[1] https://www.anneysen.com/ilk-yil/makale/bebek-gelisimi-bebeklerde-boy-kilo-nasil-olmali_11319